export const LOAD_RECENT = "LOAD_RECENT";
export const DELETE_WATCH_URL = "DELETE_WATCH_URL";
export const ACKNOWLEDGE = "ACKNOWLEDGE";
export const LOAD_MONTHLY_DETAILED = "LOAD_MONTHLY_DETAILED";
export const LOAD_MONTHLY_AGG = "LOAD_MONTHLY_AGG";
export const STOP_LOADING = "STOP_LOADING";
export const START_LOADING = "START_LOADING";
